name: Lightful
favicon: null
layout_spectrum: 0.78727
typography_spectrum: 0.57995
title: Your cause. Your platform.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0059ff'
    - '#1d1d1b'
    - '#fffd84'
    - '#ff1ea7'
    - '#ff7300'
  brandStrength: 0.75
  lightness: 0.06871518422849476
  saturation: 0.5
  rhythmicContrast: 0.6537812284659594
purpose: []
